services:
  - type: web
    name: tandonia-backend
    env: node
    branch: master
    buildCommand: "cd .. && npm install"
    startCommand: "cd .. && node \"tandonia_backend.js\""
    plan: free
    autoDeploy: true
    envVars: []
  - type: static
    name: tandonia-frontend
    env: static
    branch: master
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/dist"
    plan: free
    autoDeploy: true
    envVars: []